# Generated by Django 5.1.4 on 2025-05-05 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('experience', models.IntegerField(verbose_name='Опыт работы (лет)')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тренировки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('duration', models.IntegerField(verbose_name='Длительность (минуты)')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('max_participants', models.IntegerField(verbose_name='Максимальное количество участников')),
                ('current_participants', models.IntegerField(default=0, verbose_name='Текущее количество участников')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.trainer', verbose_name='Тренер')),
                ('workout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.workouttype', verbose_name='Тип тренировки')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.schedule', verbose_name='Расписание')),
            ],
            options={
                'unique_together': {('user', 'schedule')},
            },
        ),
    ]
